services:
  oms-landing:
    build:
      context: .
    image: oms-landing
    container_name: oms-landing
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.oms.rule=Host(`ourmicroschool.com`) || Host(`www.ourmicroschool.com`)"
      - "traefik.http.routers.oms.entrypoints=websecure"
      - "traefik.http.routers.oms.tls=true"
      - "traefik.http.routers.oms.tls.certresolver=myresolver"
      - "traefik.http.services.oms.loadbalancer.server.port=3000"
    restart: always
    networks:
      - internal

  oms-identity:
    build:
      context: ../../oms/oms-identity
    image: oms-identity
    container_name: oms-identity
    env_file:
      - ../../oms/oms-identity/.env
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.oms-identity.rule=Host(`identity-api.ourmicroschool.com`)"
      - "traefik.http.routers.oms-identity.entrypoints=websecure"
      - "traefik.http.routers.oms-identity.tls=true"
      - "traefik.http.routers.oms-identity.tls.certresolver=myresolver"
      - "traefik.http.services.oms-identity.loadbalancer.server.port=8001"
    restart: always
    networks:
      - internal

  oms-content:
    build:
      context: ../../oms/oms-content
    image: oms-content
    container_name: oms-content
    env_file:
      - ../../oms/oms-content/.env
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.oms-content.rule=Host(`content-api.ourmicroschool.com`)"
      - "traefik.http.routers.oms-content.entrypoints=websecure"
      - "traefik.http.routers.oms-content.tls=true"
      - "traefik.http.routers.oms-content.tls.certresolver=myresolver"
      - "traefik.http.services.oms-content.loadbalancer.server.port=8002"
    restart: always
    networks:
      - internal

  oms-admin:
    build:
      context: ../../oms/oms-admin
    image: oms-admin
    container_name: oms-admin
    env_file:
      - ../../oms/oms-admin/.env.local
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.oms-admin.rule=Host(`admin.ourmicroschool.com`)"
      - "traefik.http.routers.oms-admin.entrypoints=websecure"
      - "traefik.http.routers.oms-admin.tls=true"
      - "traefik.http.routers.oms-admin.tls.certresolver=myresolver"
      - "traefik.http.services.oms-admin.loadbalancer.server.port=3004"
    restart: always
    networks:
      - internal

  oms-app:
    build:
      context: ../../oms/oms-app
    image: oms-app
    container_name: oms-app
    env_file:
      - ../../oms/oms-app/.env.local
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.oms-app.rule=Host(`app.ourmicroschool.com`)"
      - "traefik.http.routers.oms-app.entrypoints=websecure"
      - "traefik.http.routers.oms-app.tls=true"
      - "traefik.http.routers.oms-app.tls.certresolver=myresolver"
      - "traefik.http.services.oms-app.loadbalancer.server.port=3001"
    restart: always
    networks:
      - internal

  oms-classrooms:
    build:
      context: ../../oms/oms-classrooms
    image: oms-classrooms
    container_name: oms-classrooms
    env_file:
      - ../../oms/oms-classrooms/.env.local
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.oms-classrooms.rule=Host(`classrooms.ourmicroschool.com`)"
      - "traefik.http.routers.oms-classrooms.entrypoints=websecure"
      - "traefik.http.routers.oms-classrooms.tls=true"
      - "traefik.http.routers.oms-classrooms.tls.certresolver=myresolver"
      - "traefik.http.services.oms-classrooms.loadbalancer.server.port=3002"
    restart: always
    networks:
      - internal

  reverse-proxy:
    image: traefik:v3.2
    container_name: reverse-proxy
    networks:
      - internal
      - default
    command:
      - "--api.insecure=true"
      - "--api.dashboard=true"
      - "--providers.docker"
      - "--providers.docker.exposedbydefault=false"
      - "--entryPoints.websecure.address=:443"
      - "--certificatesresolvers.myresolver.acme.httpchallenge=true"
      - "--certificatesresolvers.myresolver.acme.httpchallenge.entrypoint=web"
      - "--certificatesresolvers.myresolver.acme.email=yonit.anosie@ourmicroschool.com"
      - "--certificatesresolvers.myresolver.acme.storage=/letsencrypt/acme.json"
      - "--entryPoints.web.address=:80"
      - "--entryPoints.web.http.redirections.entryPoint.to=websecure"
      - "--entryPoints.web.http.redirections.entryPoint.scheme=https"
    ports:
      - "80:80"
      - "443:443"
      - "8080:8080"
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock"
      - "/letsencrypt:/letsencrypt"
    restart: always

networks:
  internal:
    name: internal

volumes:
  letsencrypt:
